# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
ratio          = [ 1, 2, 3 ]
sort_sensitive = true
linemode       = "permissions"
show_hidden    = true
scrolloff      = 10
mouse_events   = [  ]
title_format   = "yazi: {cwd}"

# : }}}

# : Preview {{{

[preview]
tab_size      = 4
max_width     = 1000
max_height    = 1000
image_delay   = 50
image_quality = 50

# : }}}

# : Input {{{

[input]
cursor_blink = true

# cd
cd_title  = "─ cd: ─"
cd_origin = "bottom-left"
cd_offset = [ 0, 0, 26, 3 ]

# create
create_title  = [ "─ Create: ─", "─ Create (dir): ─" ]
create_origin = "hovered"
create_offset = [ 0, 1, 51, 3 ]

# rename
rename_title  = "─ Rename: ─"
rename_offset = [ 0, 1, 51, 3 ]

# filter
filter_title  = "─ Filter: ─"
filter_origin = "bottom-left"
filter_offset = [ 0, 0, 26, 3 ]

# find
find_title  = [ "─ /: ─", "─ ?: ─" ]
find_origin = "bottom-left"
find_offset = [ 0, 0, 26, 3 ]

# search
search_title  = "─ {n}: ─"
search_origin = "bottom-left"
search_offset = [ 0, 0, 26, 3 ]

# shell
shell_origin = "bottom-left"
shell_offset = [ 0, 0, 26, 3 ]
shell_title  = [ "─ ; ─", "─ : ─" ]

# : }}}

# : Confirm {{{

[confirm]
#trash
trash_title  = "─ Trash {n} selected files? ─"
trash_offset = [ 0, 0, 51, 14 ]

# delete
delete_title  = "─ Delete {n} selected files? ─"
delete_offset = [ 0, 0, 51, 14 ]

# overwrite
overwrite_title  = "─ Overwrite file? ─"
overwrite_offset = [ 0, 0, 51, 14 ]

# quit
quit_title  = "─ Quit? ─"
quit_body   = "The following tasks are still running,\nare you sure you want to quit?"
quit_offset = [ 0, 0, 51, 14 ]

# : }}}

# : Pick {{{

[pick]
open_title  = "─ Open with: ─"
open_offset = [ 0, 1, 51, 3 ]

# : }}}

# : Which {{{

[which]
sort_by        = "key"
sort_sensitive = true

# : }}}

# : Plugin {{{

# https://github.com/yazi-rs/plugins/tree/main/git.yazi
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

# : }}}
